version: '2.0'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_DB=acquereur
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  backend:
    image: backend
    build: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 8888:8888
    # depends_on:
    #   - mongodb
    links:
      - mongodb
