version: '3.3'

services:
  db_acquereur:
    image: mongo:latest
    container_name: db_acquereur
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_DB=acquereur
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  backend_acquereur:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_acquereur
    environment:
      - NODE_ENV=production
      - MONGO_SERVER=db_acquereur
    ports:
      - 8888:8888
    depends_on:
      - db_acquereur
